### ISSUE TITLE
pass the file to python 

### ISSUE THREAD

**Issue by 12345Mohamed** [RomuloOliveira/monte-carlo-cvrp#13]
Dear Mr. Romulo,
good day
Please i need your support to know how to give the path to the file used for the Python language after the attachedscreen appears,
![2](https://user-images.githubusercontent.com/48835045/84570271-488e8280-ad41-11ea-813e-f6d8e1db1887.png) 
or please i need your support to know how to give the input file and get the output file 

Best Regards
Mohamed

**Comment by RomuloOliveira** [comment]
Hi, @12345Mohamed, it appears that you're opening your Python shell without passing the command. The script accepts commands in the form `python run.py <input_path> <vehicles_number>`

If that's the situation, try to open a terminal command line, then go to repository base directory and run the following command to test:

```
python run.py input/Augerat/A-n32-k5.vrp 5
```

If it works, you can replace the input and vehicles number with your desired inputs.

Note that when this project was made, it was using Python 2.7 and it may not work with Python 3.

**Comment by 12345Mohamed** [comment]
Dear Mr. Romulo

First of all, I would like to thank you for your prompt response and support.



Please note that I downloaded version 2.7 of the Python program and ran the program through the command line and still there is an issue, the attached result appeared in the email and I also added a copy of the program in the attachments because I modified the print command from print”” to print(“”) in all files because it was not working properly.



Please advise



Best Regards



Mohamed


________________________________
من: Rômulo Oliveira <notifications@github.com>
‏‏تم الإرسال: 22/شوال/1441 10:37 م
إلى: RomuloOliveira/monte-carlo-cvrp <monte-carlo-cvrp@noreply.github.com>
نسخة: 12345Mohamed <mohamed_said_3ppass@hotmail.com>; Mention <mention@noreply.github.com>
‏‏الموضوع: Re: [RomuloOliveira/monte-carlo-cvrp] pass the file to python (#13)


Hi, @12345Mohamed<https://github.com/12345Mohamed>, it appears that you're opening your Python shell without passing the command. The script accepts commands in the form python run.py <input_path> <vehicles_number>

If that's the situation, try to open a terminal command line, then go to repository base directory and run the following command to test:

python run.py input/Augerat/A-n32-k5.vrp 5


If it works, you can replace the input and vehicles number with your desired inputs.

Note that when this project was made, it was using Python 2.7 and it may not work with Python 3.

**Comment by RomuloOliveira** [comment]
I've seen in #14 that you were able to call the example file. I'll resolve this issue, let's keep #14 open to fix your other problem.
